name       : wayland-utils
version    : 1.1.0
release    : 1
source     :
    - https://gitlab.freedesktop.org/wayland/wayland-utils/-/archive/1.1.0/wayland-utils-1.1.0.tar.gz : 736fae5eb93e7eb6cdaa2374583b82912d2a497853ee8a1b3aeec0109ddd82dc
license    :
    - X11
    - MIT
component  : system.utils
summary    : wayland-info is a utility for displaying information about the Wayland protocols supported by a Wayland compositor.
description: |
    wayland-info is a utility for displaying information about the Wayland protocols supported by a Wayland compositor. It can be used to check which Wayland protocols and versions are advertised by the Wayland compositor. wayland-info also provides additional information for a subset of Wayland protocols it knows about, namely Linux DMABUF, presentation time, tablet and XDG output protocols.
builddeps  :
    - pkgconfig(libdrm)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
